'use client';

export const DEMO_STATIONS = [
  {
    id: '1',
    name: 'YoFi TV Sleep',
    subtitle: 'Ambient Music',
    description: 'Peaceful ambient soundscapes and lo-fi beats for deep sleep and relaxation',
    categories: ['Sleep', 'Ambient', 'Relaxation'],
    about: 'Curated collection of ambient music and lo-fi beats designed to help you fall asleep and stay asleep. New content added weekly.',
    tier: 'featured',
    logo: '/station_logos/YoFi_TV_Sleep.png',
    videos: [
      { id: '1', title: 'Deep Sleep', url: 'https://youtu.be/lh4JdZTJe7k?si=gtphm9LdtAuNxH5s', duration: 480 },
      { id: '2', title: 'Calm Sleep', url: 'https://youtu.be/v-Ryb13PUIs?si=SFv77-Y-cjJ_GZ5b', duration: 480 },
      { id: '3', title: 'White Noise', url: 'https://www.youtube.com/watch?v=WfFFDXAVUjA', duration: 480 },
      { id: '4', title: 'Dream of Electric Sleep', url: 'https://youtu.be/dylMO2buCXA?si=-2NSFWl5LgzjXQyT', duration: 480 },
      { id: '5', title: 'The Blue Forest', url: 'https://www.youtube.com/watch?v=FIMdEPd98xs', duration: 480 },
    ],
  },
  {
    id: '2',
    name: 'YoFi TV Study',
    subtitle: 'Focus Music',
    description: 'Productive beats and focus music for work and studying',
    categories: ['Study', 'Productivity', 'Focus'],
    about: 'The perfect background music for studying, working, or deep focus. Scientifically designed to help you concentrate without distraction.',
    tier: 'partnered',
    logo: '/station_logos/YoFi_TV_Study.png',
    videos: [
      { id: '1', title: "90's Lo-Fi Study & Chill", url: 'https://www.youtube.com/watch?v=sF80I-TQiW0', duration: 480 },
      { id: '2', title: 'Workspace Lo-Fi Study & Chill', url: 'https://www.youtube.com/watch?v=Q89Dzox4jAE', duration: 480 },
      { id: '3', title: 'Deep Focus Lo-Fi Study & Concentration', url: 'https://www.youtube.com/watch?v=p_LcrQeZzwI', duration: 480 },
      { id: '4', title: 'Synthwave Study Session', url: 'https://youtu.be/utT6c323pxo?si=1RlkZ_2TKdYkquA9', duration: 480 },
      { id: '5', title: 'Coffee & Cafe Study & Relax', url: 'https://youtu.be/Gvx-DAzR-4k?si=p2tZfNSdrgkqYFKN', duration: 480 },
    ],
  },
  {
    id: '3',
    name: 'YoFi TV Rain',
    subtitle: 'Nature Sounds',
    description: 'Calming rain and nature sounds for meditation and relaxation',
    categories: ['Rain', 'Nature', 'Ambient'],
    about: 'Peaceful rain and thunderstorm sounds. Perfect for sleep, meditation, or a calming background ambience anytime.',
    tier: 'verified',
    logo: '/station_logos/YoFi_TV_Rain.png',
    videos: [
      { id: '1', title: 'Autumn Forest Rain', url: 'https://www.youtube.com/watch?v=Go4YMAws6BU', duration: 480 },
      { id: '2', title: 'Rain & Thunderstorms', url: 'https://www.youtube.com/watch?v=ekXFslHOvZ8', duration: 480 },
      { id: '3', title: 'Japanese Zen Garden Rain', url: 'https://www.youtube.com/watch?v=YN6wj5NfOnM', duration: 480 },
      { id: '4', title: 'Heavy Rain, Thunder, & Ocean', url: 'https://www.youtube.com/watch?v=VcsEA0zl8LU', duration: 480 },
      { id: '5', title: 'Dark Bedroom Rain', url: 'https://www.youtube.com/watch?v=umYE_5LYg5I&t=12s', duration: 480 },
    ],
  },
  {
    id: '4',
    name: 'YoFi TV Fireplace',
    subtitle: 'Cozy Vibes',
    description: 'Warm fireplace ambience and crackling fire sounds for comfort',
    categories: ['Cozy', 'Fireplace', 'Ambient'],
    about: 'The warmth and comfort of a fireplace, right in your home. Perfect for winter nights, cozy afternoons, or anytime you need comfort.',
    tier: 'verified',
    logo: '/station_logos/YoFi_TV_Fireplace.png',
    videos: [
      { id: '1', title: 'Cozy Fireplace', url: 'https://www.youtube.com/watch?v=CIj-ZDSjZ2E', duration: 480 },
      { id: '2', title: 'Crackling Fire', url: 'https://www.youtube.com/watch?v=e_9ugz11-Ds', duration: 480 },
      { id: '3', title: 'Fire by the Lake', url: 'https://www.youtube.com/watch?v=mwf1vgCgMLw', duration: 480 },
      { id: '4', title: 'Cozy Campfire at Night', url: 'https://www.youtube.com/watch?v=sZzdM3b7lPE', duration: 480 },
      { id: '5', title: 'Rocky Mountain Campfire', url: 'https://www.youtube.com/watch?v=uieyh-CcJ5Y', duration: 480 },
    ],
  },
  {
    id: '5',
    name: 'YoFi TV Voyage',
    subtitle: 'Travel & Exploration',
    description: 'Adventures, travel journeys, and scenic explorations around the world',
    categories: ['Travel', 'Adventure', 'Exploration'],
    about: 'Journey around the world through scenic videos and travel experiences. Explore beautiful places, cultures, and landscapes from your couch.',
    tier: 'verified',
    logo: '/station_logos/YoFi_TV_Voyage.png',
    videos: [
      { id: '1', title: 'Train Journey through Switzerland', url: 'https://www.youtube.com/watch?v=ADt_RisXY0U', duration: 480 },
      { id: '2', title: 'Tropical Boat Ride', url: 'https://youtu.be/ffb37mJXwC0?si=k8V24fGDtBWdNuRS', duration: 480 },
      { id: '3', title: 'Snowy Norwegian Train Ride', url: 'https://www.youtube.com/watch?v=GxCb0pgO9Ig', duration: 480 },
      { id: '4', title: 'Redwood Forest Walk', url: 'https://www.youtube.com/watch?v=q9rQTB_Qr0A', duration: 480 },
      { id: '5', title: 'Flight of the Eagle', url: 'https://www.youtube.com/watch?v=9-wOXQiQ0Tw', duration: 480 },
    ],
  },
];